[font]
size = 10.5

[font.bold]
family = "IosevkaTerm NFP"

[font.bold_italic]
family = "IosevkaTerm NFP"
style = "Italic"

[font.italic]
family = "IosevkaTerm NFP"
style = "Light Italic"

[font.normal]
family = "IosevkaTerm NFP"
style = "Light"
