[font]
size = 12

[font.bold]
family = "IosevkaTerm Nerd Font"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"

[font.italic]
family = "IosevkaTerm Nerd Font"

[font.normal]
family = "IosevkaTerm Nerd Font"
